/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import dao.EquipoDAO;
import modelo.Equipo;
import modelo.Usuario;
import util.Sesion;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 1
 */
public class IFCrearEquipo extends javax.swing.JInternalFrame {

    private IFMiEquipo miEquipo;
    private Equipo equipoActual;
    private boolean esEdicion = false;

    /**
     * Creates new form IFMiEquipo
     */
    public IFCrearEquipo() {
        initComponents();
        txtImagen.setEditable(false);
        esEdicion = false;
        btnCrear.setText("Crear Equipo");
    }

    public IFCrearEquipo(IFMiEquipo miEquipo) {
        this();
        this.miEquipo = miEquipo;
    }

    public IFCrearEquipo(IFMiEquipo miEquipo, Equipo equipoParaEditar) {
        this();
        this.miEquipo = miEquipo;
        this.equipoActual = equipoParaEditar;
        this.esEdicion = true;
        cargarDatosEdicion();
    }

    private void cargarDatosEdicion() {
        if (equipoActual == null) return;

        jLabel5.setText("Editar Equipo");
        btnCrear.setText("Actualizar Equipo");

        txtNombre.setText(equipoActual.getNombre());
        txtCiudad.setText(equipoActual.getCiudad());

        if (equipoActual.getLogo() != null && !equipoActual.getLogo().isBlank()) {
            txtImagen.setText(equipoActual.getLogo());
            mostrarVistaPrevia(equipoActual.getLogo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        btnImage = new javax.swing.JButton();
        txtImagen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.black);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ciudad");

        btnImage.setBackground(new java.awt.Color(255, 102, 0));
        btnImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImage.setForeground(new java.awt.Color(255, 255, 255));
        btnImage.setText("Cargar imagen");
        btnImage.addActionListener(this::btnImageActionPerformed);

        txtImagen.addActionListener(this::txtImagenActionPerformed);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar logo");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Crear Equipo");

        btnCrear.setBackground(new java.awt.Color(255, 102, 0));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear Equipo");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImagen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnImage))
                                .addGap(0, 53, Short.MAX_VALUE)))
                        .addGap(104, 104, 104))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImage)
                .addGap(52, 52, 52)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar logo del equipo");
        chooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "png", "jpg", "jpeg", "gif", "bmp"));

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            txtImagen.setText(archivo.getAbsolutePath());
            mostrarVistaPrevia(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre = txtNombre.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String logo = txtImagen.getText().trim();

        if (nombre.isEmpty() || ciudad.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debes completar el nombre y la ciudad del equipo.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Sesion.getInstancia().estaLogueado() || Sesion.getInstancia().getUsuario() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes iniciar sesión para crear un equipo.",
                    "Sesión requerida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (esEdicion) {
            actualizarEquipo(nombre, ciudad, logo);
        } else {
            crearEquipo(nombre, ciudad, logo);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void crearEquipo(String nombre, String ciudad, String logo) {
        try {
            Usuario usuario = Sesion.getInstancia().getUsuario();
            EquipoDAO dao = new EquipoDAO();
            if (dao.buscarPorUsuario(usuario.getIdUsuario()) != null) {
                JOptionPane.showMessageDialog(this,
                        "Ya tienes un equipo registrado.",
                        "Equipo existente",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Equipo equipo = new Equipo(
                    0,
                    nombre,
                    ciudad,
                    usuario.getIdUsuario(),
                    logo.isBlank() ? null : logo,
                    LocalDate.now().toString(),
                    1,
                    usuario.getNombre()
            );

            if (dao.insertar(equipo)) {
                JOptionPane.showMessageDialog(this,
                        "Equipo creado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                if (miEquipo != null) {
                    miEquipo.recargar();
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo crear el equipo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar el equipo:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarEquipo(String nombre, String ciudad, String logo) {
        try {
            if (equipoActual == null) return;

            equipoActual.setNombre(nombre);
            equipoActual.setCiudad(ciudad);
            equipoActual.setLogo(logo.isBlank() ? null : logo);

            EquipoDAO dao = new EquipoDAO();
            if (dao.actualizar(equipoActual)) {
                JOptionPane.showMessageDialog(this,
                        "Equipo actualizado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                if (miEquipo != null) {
                    miEquipo.recargar();
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el equipo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar el equipo:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarVistaPrevia(String ruta) {
        File archivo = new File(ruta);
        if (!archivo.exists()) {
            jLabel1.setIcon(null);
            jLabel1.setText("Sin vista previa");
            return;
        }

        ImageIcon icono = new ImageIcon(ruta);
        if (icono.getIconWidth() <= 0) {
            jLabel1.setIcon(null);
            jLabel1.setText("Sin vista previa");
            return;
        }

        Image imagen = icono.getImage().getScaledInstance(159, 172, Image.SCALE_SMOOTH);
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(imagen));
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtCiudad.setText("");
        txtImagen.setText("");
        jLabel1.setIcon(null);
        jLabel1.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
