/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;
import dao.JugadorDAO;
import modelo.Jugador;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.EquipoDAO;
import modelo.Equipo;
import modelo.Usuario;
import util.Sesion;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 1
 */
public class IFCrearEquipo extends javax.swing.JInternalFrame {

    private IFMiEquipo miEquipo;
    private Equipo equipoActual;
    private boolean esEdicion = false;
    private boolean ocultarSeccionListados = false;

    /**
     * Creates new form IFMiEquipo
     */
    public IFCrearEquipo() {
        initComponents();
        txtImagen.setEditable(false);
        esEdicion = false;
        btnCrear.setText("Crear Equipo");
        btnImage.addActionListener(this::btnImageActionPerformed);
        btnCrear.addActionListener(this::btnCrearActionPerformed);
        ocultarSeccionListados = esCoachActual();
        configurarSeccionListados();
    }

    public IFCrearEquipo(IFMiEquipo miEquipo) {
        this();
        this.miEquipo = miEquipo;
    }

    public IFCrearEquipo(IFMiEquipo miEquipo, Equipo equipoParaEditar) {
        this();
        this.miEquipo = miEquipo;
        this.equipoActual = equipoParaEditar;
        this.esEdicion = true;
        cargarDatosEdicion();
    }

    private boolean esCoachActual() {
        return Sesion.getInstancia() != null
                && Sesion.getInstancia().estaLogueado()
                && Sesion.getInstancia().getUsuario() != null
                && Sesion.getInstancia().getUsuario().getNombreRol() != null
                && "coach".equalsIgnoreCase(Sesion.getInstancia().getUsuario().getNombreRol().trim());
    }

    private void configurarSeccionListados() {
        if (ocultarSeccionListados) {
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jScrollPane1.setVisible(false);
            jScrollPane2.setVisible(false);
            tblEquipos.setVisible(false);
            tblJugadores.setVisible(false);
            revalidate();
            repaint();
            return;
        }

        cargarEquipos();
        tblEquipos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEquipos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarJugadoresDelEquipo();
            }
        });
    }

    private void cargarDatosEdicion() {
        if (equipoActual == null) return;

        jLabel5.setText("Editar Equipo");
        btnCrear.setText("Actualizar Equipo");

        txtNombre.setText(equipoActual.getNombre());
        txtCiudad.setText(equipoActual.getCiudad());

        if (equipoActual.getLogo() != null && !equipoActual.getLogo().isBlank()) {
            txtImagen.setText(equipoActual.getLogo());
            mostrarVistaPrevia(equipoActual.getLogo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnImage = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.black);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Crear Equipo");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ciudad:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar logo:");

        txtImagen.addActionListener(this::txtImagenActionPerformed);

        btnImage.setBackground(new java.awt.Color(255, 102, 0));
        btnImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImage.setForeground(new java.awt.Color(255, 255, 255));
        btnImage.setText("Cargar imagen");

        btnCrear.setBackground(new java.awt.Color(255, 102, 0));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear Equipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCiudad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImage)
                            .addComponent(txtImagen))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImage))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addGap(42, 42, 42))
        );

        tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEquipos);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setText("Equipos Existentes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel6)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setText("Jugadores");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel7)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblJugadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel5)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(568, 568, 568))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar logo del equipo");
        chooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "png", "jpg", "jpeg", "gif", "bmp"));

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            txtImagen.setText(archivo.getAbsolutePath());
            mostrarVistaPrevia(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre = txtNombre.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String logo = txtImagen.getText().trim();

        if (nombre.isEmpty() || ciudad.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debes completar el nombre y la ciudad del equipo.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Sesion.getInstancia().estaLogueado() || Sesion.getInstancia().getUsuario() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes iniciar sesión para crear un equipo.",
                    "Sesión requerida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (esEdicion) {
            actualizarEquipo(nombre, ciudad, logo);
        } else {
            crearEquipo(nombre, ciudad, logo);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void crearEquipo(String nombre, String ciudad, String logo) {
        try {
            Usuario usuario = Sesion.getInstancia().getUsuario();
            EquipoDAO dao = new EquipoDAO();
            if (dao.buscarPorUsuario(usuario.getIdUsuario()) != null) {
                JOptionPane.showMessageDialog(this,
                        "Ya tienes un equipo registrado.",
                        "Equipo existente",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Equipo equipo = new Equipo(
                    0,
                    nombre,
                    ciudad,
                    usuario.getIdUsuario(),
                    logo.isBlank() ? null : logo,
                    LocalDate.now().toString(),
                    1,
                    usuario.getNombre()
            );

            if (dao.insertar(equipo)) {
                JOptionPane.showMessageDialog(this,
                        "Equipo creado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                if (miEquipo != null) {
                    miEquipo.recargar();
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo crear el equipo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar el equipo:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarEquipo(String nombre, String ciudad, String logo) {
        try {
            if (equipoActual == null) return;

            equipoActual.setNombre(nombre);
            equipoActual.setCiudad(ciudad);
            equipoActual.setLogo(logo.isBlank() ? null : logo);

            EquipoDAO dao = new EquipoDAO();
            if (dao.actualizar(equipoActual)) {
                JOptionPane.showMessageDialog(this,
                        "Equipo actualizado correctamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                if (miEquipo != null) {
                    miEquipo.recargar();
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el equipo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar el equipo:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarVistaPrevia(String ruta) {
        File archivo = new File(ruta);
        if (!archivo.exists()) {
            jLabel1.setIcon(null);
            jLabel1.setText("Sin vista previa");
            return;
        }

        ImageIcon icono = new ImageIcon(ruta);
        if (icono.getIconWidth() <= 0) {
            jLabel1.setIcon(null);
            jLabel1.setText("Sin vista previa");
            return;
        }

        Image imagen = icono.getImage().getScaledInstance(159, 172, Image.SCALE_SMOOTH);
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(imagen));
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtCiudad.setText("");
        txtImagen.setText("");
        jLabel1.setIcon(null);
        jLabel1.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTable tblJugadores;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

private void cargarEquipos() {
    try {
        List<Equipo> lista = new EquipoDAO().listar();
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Ciudad", "Director"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        for (Equipo eq : lista) {
            model.addRow(new Object[]{
                eq.getIdEquipo(),
                eq.getNombre(),
                eq.getCiudad(),
                eq.getNombreDirector()
            });
        }
        tblEquipos.setModel(model);
        tblEquipos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEquipos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblEquipos.getColumnModel().getColumn(0).setMinWidth(0); // ocultar ID

        if (model.getRowCount() > 0) {
            tblEquipos.setRowSelectionInterval(0, 0);
        } else {
            tblJugadores.setModel(new DefaultTableModel(new Object[]{"Nombre", "Apellido", "Posición", "Dorsal"}, 0) {
                @Override public boolean isCellEditable(int r, int c) { return false; }
            });
            jLabel7.setText("Jugadores");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar equipos: " + ex.getMessage());
    }
}

private void cargarJugadoresDelEquipo() {
    int fila = tblEquipos.getSelectedRow();
    if (fila < 0) {
        return;
    }

    int idEquipo = (int) tblEquipos.getValueAt(fila, 0);

    try {
        List<Jugador> jugadores = new JugadorDAO().listarPorEquipo(idEquipo);
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Nombre", "Apellido", "Posición", "Dorsal"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        for (Jugador j : jugadores) {
            model.addRow(new Object[]{
                j.getNombre(),
                j.getApellido(),
                j.getPosicion(),
                j.getNumeroCamiseta()
            });
        }
        tblJugadores.setModel(model);
        jLabel7.setText("Jugadores — " + tblEquipos.getValueAt(fila, 1));
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar jugadores: " + ex.getMessage());
    }
}
}
