/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import dao.EquipoDAO;
import dao.TorneoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;
import modelo.Torneo;
import util.Sesion;

/**
 *
 * @author admin
 */
public class IFInscribir extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFInscribir
     */
    
    private TorneoDAO torneoDAO = new TorneoDAO();
    private EquipoDAO equipoDAO = new EquipoDAO();
    private DefaultTableModel modelo;
    private List<Torneo> torneosCargados;
    public IFInscribir() {
        initComponents();
        torneosCargados = new ArrayList<>();
        inicializarTabla();
        cargarTorneosActivos();
        jButton1.addActionListener(e -> inscribirEquipoEnTorneo());
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrarTorneos(jTextField1.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Inscribirse en un torneo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inscribirse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(232, 232, 232))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {
        modelo = new DefaultTableModel(new Object[]{"ID", "Nombre", "Ubicación", "Fecha Inicio"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modelo);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
    }

    private void cargarTorneosActivos() {
        try {
            torneosCargados.clear();
            modelo.setRowCount(0);

            List<Torneo> torneos = torneoDAO.listarActivos();
            for (Torneo t : torneos) {
                torneosCargados.add(t);
                String fechaInicio = t.getFechaInicio() != null ? t.getFechaInicio().toString() : "-";
                modelo.addRow(new Object[]{
                    t.getIdTorneo(),
                    t.getNombre(),
                    t.getUbicacion() != null ? t.getUbicacion() : "-",
                    fechaInicio
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error cargando torneos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrarTorneos(String texto) {
        modelo.setRowCount(0);
        String filtro = texto.toLowerCase();

        for (Torneo t : torneosCargados) {
            if (t.getNombre().toLowerCase().contains(filtro) || 
                (t.getUbicacion() != null && t.getUbicacion().toLowerCase().contains(filtro))) {
                String fechaInicio = t.getFechaInicio() != null ? t.getFechaInicio().toString() : "-";
                modelo.addRow(new Object[]{
                    t.getIdTorneo(),
                    t.getNombre(),
                    t.getUbicacion() != null ? t.getUbicacion() : "-",
                    fechaInicio
                });
            }
        }
    }

    private void inscribirEquipoEnTorneo() {
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un torneo para inscribirse.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Sesion.getInstancia().estaLogueado() || Sesion.getInstancia().getUsuario() == null) {
            JOptionPane.showMessageDialog(this, "Debes iniciar sesión para inscribir tu equipo.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Equipo equipo = equipoDAO.buscarPorUsuario(Sesion.getInstancia().getUsuario().getIdUsuario());
            if (equipo == null) {
                JOptionPane.showMessageDialog(this, "No tienes un equipo activo. Crea uno primero.", "Sin equipo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idTorneo = (int) jTable1.getValueAt(filaSeleccionada, 0);
            Torneo torneoSeleccionado = null;
            for (Torneo t : torneosCargados) {
                if (t.getIdTorneo() == idTorneo) {
                    torneoSeleccionado = t;
                    break;
                }
            }

            if (torneoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el torneo seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (torneoDAO.inscribirEquipo(equipo.getIdEquipo(), idTorneo)) {
                JOptionPane.showMessageDialog(this,
                    "¡Tu equipo se ha inscrito correctamente en el torneo '" + torneoSeleccionado.getNombre() + "'!",
                    "Inscripción exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
                cargarTorneosActivos();
                jTextField1.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo completar la inscripción. Es posible que ya esté inscrito.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al inscribir tu equipo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
