/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.EquipoDAO;
import dao.PartidoDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;
import modelo.Partido;
import util.Sesion;

/**
 *
 * @author admin
 */
public class IFPartidosCoach extends javax.swing.JInternalFrame {

    private final PartidoDAO partidoDAO = new PartidoDAO();
    private final EquipoDAO equipoDAO = new EquipoDAO();
    private DefaultTableModel modeloPendientes;
    private DefaultTableModel modeloFinalizados;
    private java.util.List<Partido> listaPendientes;
    private java.util.List<Partido> listaFinalizados;

    /**
     * Creates new form IFPartidosCoach
     */
    public IFPartidosCoach() {
        initComponents();
        inicializarTablas();
        // Registrar listeners antes de cargar datos para que la selección inicial dispare eventos
        agregarListenersTablas();
        btnReportePendiente.addActionListener(this::btnReportePendienteActionPerformed);
        btnReporteFinalizado.addActionListener(this::btnReporteFinalizadoActionPerformed);
        cargarPartidosDelCoach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnReportePendiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtpDetallePartido = new javax.swing.JTextPane();
        btnReporteFinalizado = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Partidos pendientes");

        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setBorder(null);
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextPane1);

        btnReportePendiente.setBackground(new java.awt.Color(255, 102, 0));
        btnReportePendiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportePendiente.setForeground(new java.awt.Color(255, 255, 255));
        btnReportePendiente.setText("Descargar Reporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReportePendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnReportePendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pendientes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Partidos Finalizados");

        txtpDetallePartido.setBackground(new java.awt.Color(0, 0, 0));
        txtpDetallePartido.setBorder(null);
        txtpDetallePartido.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(txtpDetallePartido);

        btnReporteFinalizado.setBackground(new java.awt.Color(255, 102, 0));
        btnReporteFinalizado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteFinalizado.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteFinalizado.setText("Descargar Reportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btnReporteFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnReporteFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Finalizados", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTablas() {
        modeloPendientes = new DefaultTableModel(new Object[]{"ID", "Local", "Visitante", "Fecha", "Lugar"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        jTable1.setModel(modeloPendientes);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setRowSelectionAllowed(true);
        jTable1.setColumnSelectionAllowed(false);

        modeloFinalizados = new DefaultTableModel(new Object[]{"ID", "Local", "Visitante", "Fecha", "Lugar", "Resultado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        jTable2.setModel(modeloFinalizados);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setRowSelectionAllowed(true);
        jTable2.setColumnSelectionAllowed(false);
        // Configurar text pane para mostrar detalles
        txtpDetallePartido.setEditable(false);
        txtpDetallePartido.setOpaque(true);
        txtpDetallePartido.setBackground(new java.awt.Color(0, 0, 0));
        txtpDetallePartido.setForeground(new java.awt.Color(255, 255, 255));
        // Configurar también jTextPane1 (Pendientes)
        jTextPane1.setEditable(false);
        jTextPane1.setOpaque(true);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
    }

    private void cargarPartidosDelCoach() {
        if (!Sesion.getInstancia().estaLogueado() || Sesion.getInstancia().getUsuario() == null) {
            JOptionPane.showMessageDialog(this, "Debes iniciar sesión para ver tus partidos.", "Sesión requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Equipo equipo = equipoDAO.buscarPorUsuario(Sesion.getInstancia().getUsuario().getIdUsuario());
            if (equipo == null) {
                JOptionPane.showMessageDialog(this, "No tienes un equipo asignado.", "Sin equipo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            List<Partido> partidos = partidoDAO.listarPorEquipo(equipo.getIdEquipo());

            modeloPendientes.setRowCount(0);
            modeloFinalizados.setRowCount(0);
            if (listaPendientes == null) listaPendientes = new java.util.ArrayList<>(); else listaPendientes.clear();
            if (listaFinalizados == null) listaFinalizados = new java.util.ArrayList<>(); else listaFinalizados.clear();

            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            for (Partido p : partidos) {
                String fecha = p.getFecha() != null ? p.getFecha().format(df) : "-";
                String lugar = p.getLugar() != null ? p.getLugar() : "-";
                String estado = p.getEstadoResultado() != null ? p.getEstadoResultado() : "";
                if ("pendiente".equalsIgnoreCase(estado)) {
                    modeloPendientes.addRow(new Object[]{p.getIdPartido(), p.getNombreEquipoLocal(), p.getNombreEquipoVisit(), fecha, lugar});
                    listaPendientes.add(p);
                } else {
                    String resultado = p.getPuntosLocal() + " - " + p.getPuntosVisit();
                    modeloFinalizados.addRow(new Object[]{p.getIdPartido(), p.getNombreEquipoLocal(), p.getNombreEquipoVisit(), fecha, lugar, resultado});
                    listaFinalizados.add(p);
                }
            }

            // ocultar columna ID visualmente
            if (jTable1.getColumnModel().getColumnCount() > 0) {
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(0).setWidth(0);
            }
            if (jTable2.getColumnModel().getColumnCount() > 0) {
                jTable2.getColumnModel().getColumn(0).setMinWidth(0);
                jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable2.getColumnModel().getColumn(0).setWidth(0);
            }

            // Si hay partidos pendientes, seleccionar la primera fila para disparar el listener y mostrar detalle
            if (modeloPendientes.getRowCount() > 0) {
                try {
                    jTable1.setRowSelectionInterval(0, 0);
                } catch (Exception ex) {
                    // ignore
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error cargando partidos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void agregarListenersTablas() {
        // Cuando cambie la selección en la tabla de pendientes
        jTable1.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                int viewRow = jTable1.getSelectedRow();
                if (viewRow >= 0) {
                    int modelRow = jTable1.convertRowIndexToModel(viewRow);
                    if (listaPendientes != null && modelRow >= 0 && modelRow < listaPendientes.size()) {
                        Partido p = listaPendientes.get(modelRow);
                        mostrarDetallePartido(p, jTextPane1);
                        return;
                    }
                    // Fallback: intentar leer ID directamente del modelo
                    try {
                        Object idObj = jTable1.getModel().getValueAt(modelRow, 0);
                        if (idObj != null) {
                            int idPartido = Integer.parseInt(idObj.toString());
                            mostrarDetallePartido(idPartido, jTextPane1);
                        }
                    } catch (Exception ex) {
                        // ignore
                    }
                }
            }
        });

        // Tabla de finalizados también muestra detalles
        jTable2.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                int viewRow = jTable2.getSelectedRow();
                if (viewRow >= 0) {
                    int modelRow = jTable2.convertRowIndexToModel(viewRow);
                    if (listaFinalizados != null && modelRow >= 0 && modelRow < listaFinalizados.size()) {
                        Partido p = listaFinalizados.get(modelRow);
                        mostrarDetallePartido(p, txtpDetallePartido);
                        return;
                    }
                    try {
                        Object idObj = jTable2.getModel().getValueAt(modelRow, 0);
                        if (idObj != null) {
                            int idPartido = Integer.parseInt(idObj.toString());
                            mostrarDetallePartido(idPartido, txtpDetallePartido);
                        }
                    } catch (Exception ex) {
                        // ignore
                    }
                }
            }
        });
    }

    private void mostrarDetallePartido(int idPartido, javax.swing.JTextPane textPane) {
        try {
            Partido p = partidoDAO.buscarPorId(idPartido);
            if (p == null) {
                textPane.setText("No se encontró el partido seleccionado.");
                return;
            }
            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            StringBuilder sb = new StringBuilder();
            sb.append("Partido: ").append(p.getNombreEquipoLocal()).append(" vs ").append(p.getNombreEquipoVisit()).append('\n');
            sb.append("Fecha: ").append(p.getFecha() != null ? p.getFecha().format(df) : "-").append('\n');
            sb.append("Lugar: ").append(p.getLugar() != null ? p.getLugar() : "-").append('\n');
            sb.append("Torneo: ").append(p.getNombreTorneo() != null ? p.getNombreTorneo() : "-").append('\n');
            sb.append("Árbitro: ").append(p.getNombreArbitro() != null ? p.getNombreArbitro() : "-").append('\n');
            sb.append("Estado resultado: ").append(p.getEstadoResultado() != null ? p.getEstadoResultado() : "-").append('\n');
            sb.append("Resultado: ").append(p.getPuntosLocal()).append(" - ").append(p.getPuntosVisit()).append('\n');
            textPane.setText(sb.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error cargando detalle: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void mostrarDetallePartido(int idPartido) {
        mostrarDetallePartido(idPartido, txtpDetallePartido);
    }

    private void mostrarDetallePartido(Partido p, javax.swing.JTextPane textPane) {
        if (p == null) {
            textPane.setText("No se encontró el partido seleccionado.");
            return;
        }
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        StringBuilder sb = new StringBuilder();
        sb.append("Partido: ").append(p.getNombreEquipoLocal()).append(" vs ").append(p.getNombreEquipoVisit()).append('\n');
        sb.append("Fecha: ").append(p.getFecha() != null ? p.getFecha().format(df) : "-").append('\n');
        sb.append("Lugar: ").append(p.getLugar() != null ? p.getLugar() : "-").append('\n');
        sb.append("Torneo: ").append(p.getNombreTorneo() != null ? p.getNombreTorneo() : "-").append('\n');
        sb.append("Árbitro: ").append(p.getNombreArbitro() != null ? p.getNombreArbitro() : "-").append('\n');
        sb.append("Estado resultado: ").append(p.getEstadoResultado() != null ? p.getEstadoResultado() : "-").append('\n');
        sb.append("Resultado: ").append(p.getPuntosLocal()).append(" - ").append(p.getPuntosVisit()).append('\n');
        textPane.setText(sb.toString());
    }

    private void mostrarDetallePartido(Partido p) {
        mostrarDetallePartido(p, txtpDetallePartido);
    }

    private void btnReportePendienteActionPerformed(java.awt.event.ActionEvent evt) {
        generarReportePendientesPDF();
    }

    private void btnReporteFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {
        generarReporteFinalizadosPDF();
    }

    private void generarReportePendientesPDF() {
        try {
            if (listaPendientes == null || listaPendientes.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay partidos pendientes para generar el reporte.",
                        "Sin datos",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Guardar reporte PDF de partidos pendientes");
            chooser.setFileFilter(new FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
            chooser.setSelectedFile(new File("Reporte_Partidos_Pendientes.pdf"));

            if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
                return;
            }

            String ruta = chooser.getSelectedFile().getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }

            Equipo equipo = equipoDAO.buscarPorUsuario(Sesion.getInstancia().getUsuario().getIdUsuario());
            String nombreEquipo = equipo != null ? equipo.getNombre() : "Mi Equipo";

            Document doc = new Document(PageSize.A4);
            PdfWriter.getInstance(doc, new FileOutputStream(ruta));
            doc.open();

            Font fTitulo = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, new BaseColor(255, 102, 0));
            Font fSeccion = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, BaseColor.WHITE);
            Font fHeader = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
            Font fCelda = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.WHITE);
            Font fSub = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, new BaseColor(180, 180, 180));

            BaseColor negro = new BaseColor(0, 0, 0);
            BaseColor grisOscuro = new BaseColor(30, 30, 30);
            BaseColor naranja = new BaseColor(255, 102, 0);

            doc.add(new Paragraph(" "));

            Paragraph titulo = new Paragraph("BKB MANAGER — Reporte de Partidos Pendientes", fTitulo);
            titulo.setAlignment(Element.ALIGN_CENTER);
            titulo.setSpacingAfter(4);
            doc.add(titulo);

            Paragraph subtitulo = new Paragraph(nombreEquipo, fSeccion);
            subtitulo.setAlignment(Element.ALIGN_CENTER);
            subtitulo.setSpacingAfter(10);
            doc.add(subtitulo);

            Paragraph info = new Paragraph("Total de partidos pendientes: " + listaPendientes.size(), fSub);
            info.setAlignment(Element.ALIGN_LEFT);
            info.setSpacingAfter(12);
            doc.add(info);

            PdfPTable tabla = new PdfPTable(6);
            tabla.setWidthPercentage(100);
            tabla.setSpacingAfter(12);
            tabla.setWidths(new float[]{1.1f, 2.2f, 2.2f, 2.3f, 2.3f, 1.2f});

            String[] headers = {"ID", "Local", "Visitante", "Fecha", "Lugar", "Estado"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, fHeader));
                cell.setBackgroundColor(naranja);
                cell.setBorderColor(negro);
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }

            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            boolean alterno = false;
            for (Partido p : listaPendientes) {
                BaseColor bg = alterno ? grisOscuro : new BaseColor(15, 15, 15);
                alterno = !alterno;

                String fecha = p.getFecha() != null ? p.getFecha().format(df) : "-";
                Object[] fila = new Object[]{
                    p.getIdPartido(),
                    p.getNombreEquipoLocal(),
                    p.getNombreEquipoVisit(),
                    fecha,
                    p.getLugar() != null ? p.getLugar() : "-",
                    p.getEstadoResultado() != null ? p.getEstadoResultado() : "-"
                };

                for (Object val : fila) {
                    PdfPCell cell = new PdfPCell(new Phrase(val != null ? val.toString() : "—", fCelda));
                    cell.setBackgroundColor(bg);
                    cell.setBorderColor(new BaseColor(60, 60, 60));
                    cell.setPadding(5);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(cell);
                }
            }

            doc.add(tabla);
            doc.add(new Paragraph("Descargado: " + java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")), fSub));
            doc.close();

            JOptionPane.showMessageDialog(this,
                    "Reporte PDF generado correctamente.\n\nArchivo: " + ruta,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al generar el reporte PDF:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void generarReporteFinalizadosPDF() {
        try {
            if (listaFinalizados == null || listaFinalizados.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay partidos finalizados para generar el reporte.",
                        "Sin datos",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Guardar reporte PDF de partidos finalizados");
            chooser.setFileFilter(new FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
            chooser.setSelectedFile(new File("Reporte_Partidos_Finalizados.pdf"));

            if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
                return;
            }

            String ruta = chooser.getSelectedFile().getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }

            Equipo equipo = equipoDAO.buscarPorUsuario(Sesion.getInstancia().getUsuario().getIdUsuario());
            String nombreEquipo = equipo != null ? equipo.getNombre() : "Mi Equipo";

            Document doc = new Document(PageSize.A4);
            PdfWriter.getInstance(doc, new FileOutputStream(ruta));
            doc.open();

            Font fTitulo = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, new BaseColor(255, 102, 0));
            Font fSeccion = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, BaseColor.WHITE);
            Font fHeader = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
            Font fCelda = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.WHITE);
            Font fSub = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, new BaseColor(180, 180, 180));

            BaseColor negro = new BaseColor(0, 0, 0);
            BaseColor grisOscuro = new BaseColor(30, 30, 30);
            BaseColor naranja = new BaseColor(255, 102, 0);

            doc.add(new Paragraph(" "));

            Paragraph titulo = new Paragraph("BKB MANAGER — Reporte de Partidos Finalizados", fTitulo);
            titulo.setAlignment(Element.ALIGN_CENTER);
            titulo.setSpacingAfter(4);
            doc.add(titulo);

            Paragraph subtitulo = new Paragraph(nombreEquipo, fSeccion);
            subtitulo.setAlignment(Element.ALIGN_CENTER);
            subtitulo.setSpacingAfter(10);
            doc.add(subtitulo);

            Paragraph info = new Paragraph("Total de partidos finalizados: " + listaFinalizados.size(), fSub);
            info.setAlignment(Element.ALIGN_LEFT);
            info.setSpacingAfter(12);
            doc.add(info);

            PdfPTable tabla = new PdfPTable(8);
            tabla.setWidthPercentage(100);
            tabla.setSpacingAfter(12);
            tabla.setWidths(new float[]{0.9f, 2.0f, 2.0f, 2.0f, 1.7f, 1.2f, 1.2f, 2.0f});

            String[] headers = {"ID", "Local", "Visitante", "Fecha", "Lugar", "Pts L", "Pts V", "Ganador"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, fHeader));
                cell.setBackgroundColor(naranja);
                cell.setBorderColor(negro);
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }

            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            boolean alterno = false;
            for (Partido p : listaFinalizados) {
                BaseColor bg = alterno ? grisOscuro : new BaseColor(15, 15, 15);
                alterno = !alterno;

                String fecha = p.getFecha() != null ? p.getFecha().format(df) : "-";
                String ganador = "Empate";
                if (p.getPuntosLocal() > p.getPuntosVisit()) {
                    ganador = p.getNombreEquipoLocal() != null ? p.getNombreEquipoLocal() : "Local";
                } else if (p.getPuntosVisit() > p.getPuntosLocal()) {
                    ganador = p.getNombreEquipoVisit() != null ? p.getNombreEquipoVisit() : "Visitante";
                }

                Object[] fila = new Object[]{
                    p.getIdPartido(),
                    p.getNombreEquipoLocal(),
                    p.getNombreEquipoVisit(),
                    fecha,
                    p.getLugar() != null ? p.getLugar() : "-",
                    p.getPuntosLocal(),
                    p.getPuntosVisit(),
                    ganador
                };

                for (Object val : fila) {
                    PdfPCell cell = new PdfPCell(new Phrase(val != null ? val.toString() : "—", fCelda));
                    cell.setBackgroundColor(bg);
                    cell.setBorderColor(new BaseColor(60, 60, 60));
                    cell.setPadding(5);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(cell);
                }
            }

            doc.add(tabla);
            doc.add(new Paragraph("Descargado: " + java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")), fSub));
            doc.close();

            JOptionPane.showMessageDialog(this,
                    "Reporte PDF generado correctamente.\n\nArchivo: " + ruta,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al generar el reporte PDF:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteFinalizado;
    private javax.swing.JButton btnReportePendiente;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane txtpDetallePartido;
    // End of variables declaration//GEN-END:variables
}
